title: Material Composition
logo: /assets/img/impossible_physics1.png
description: Material composition is a repository of ideas and techniques that explore materiality through modal synthesis. It has been developed by Emiddio Vasquez as part of his PhD research.
show_downloads: true
google_analytics:
remote_theme: pages-themes/minimal
plugins:
  - jekyll-remote-theme
